sudo: required
dist: trusty

addons:
  chrome: stable

language: node_js
node_js:
  - "8"

before_script:
  - set -e
  - yarn install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn lint
  - yarn test --watch false
  - yarn e2e
  - yarn build:gh-pages

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: ./dist/client
  on:
    branch: master
